### ISSUE TITLE
Crash on Mercury

### ISSUE THREAD

**Issue by kdb424** [4-Space/4-Space-1.7#25]
Set time to day and hit issues with galacticraft. I am in a dev environment trying to work with your mod, so please feel free to contact me. I am considering forking and working on your project too if I have time.

Steps to repeat
Go to Mercury (May be other planets too)
Set time to day
Crash

Installed files
GalacticraftCore-Dev-1.7-3.0.8.104 <- and of course all other needed files to support that.
Latest 4-space from your site.

Log
http://pastebin.com/5PcVBYFJ

Side note, your lang file is slightly messed up. Pluto is appearing as planet.pluto

On second look, may net be your mod. I'll do further research.

**Comment by kdb424** [comment]
It was galacticraft. Nevermind.

**Comment by mattparks** [comment]
I was going to say, I just tested it with no error.

**Comment by mattparks** [comment]
But yea if you want to help with 4Space, I would be more than happy for you to help!

**Comment by kdb424** [comment]
Yeah, sorry. I was testing on a different version to my dev environment mistakingly. Dropping files in doesn't change loaded libraries.

Do you have a roadmap, or list of goals? Also, what is the best method to communicate? I have Google plus, and email that I primarily use.

**Comment by mattparks** [comment]
I primarily use skype. I'm mattparks5855 or mattparks5855@gmail.com, I should probably make a roadmap.

**Comment by kdb424** [comment]
https://github.com/kdb424/SpaceBees
That is my project that I am working on in case you'd like to see my work.If you wouldn't mind I would like to add some cross mod integration.

**Comment by mattparks** [comment]
That is fine if you want to add cross mod integration. I beleave you mean hive generation.

**Comment by kdb424** [comment]
Indeed. I'd like to have them generate things specific to each dimension added. More reasons to visit them all at least.

**Comment by mattparks** [comment]
Oh yea, cool, go right ahead and if you want to add anything into 4Space you can go ahead and submit a push request.

**Comment by kdb424** [comment]
Will do. I'll get it set up later. BTW, the API you used for player render. I couldn't get that to stop erroring. Which version are you using so I can get that done. I think that is the rest of the setup.

**Comment by mattparks** [comment]
Player render api?

**Comment by kdb424** [comment]
https://github.com/4-Space/4-Space-1.7/blob/7a51d003b119144947ed790946cca5a9e767f42e/src/main/java/net/smart/render/playerapi/SmartRender.java
Line 3 I had an import error.

**Comment by mattparks** [comment]
I have to update the api's just don't use the ones I've provided, use galacticrafts api's.

**Comment by kdb424** [comment]
Good to know. Thanks.
