### ISSUE TITLE
config options

### ISSUE THREAD

**Issue by Cracks777** [4-Space/4-Space-1.7#26]
can you please add config options to enable/disable planets?

**Comment by mattparks** [comment]
Ok, thats a odd request but ill see what I can do.

**Comment by Cracks777** [comment]
well i ask because other addons add the same planets/moons, i think that i have 2-3 of the same planets, lol but thank you for your time and looking into this

**Comment by mattparks** [comment]
You might want to ask the same question to the other addon's owner too.

**Comment by Cracks777** [comment]
one of them have said they are working on it.

**Comment by Cracks777** [comment]
with that said i like some of your planets over theres and the other way around too.

**Comment by mattparks** [comment]
4.1.4 adds these configs.

**Comment by Cracks777** [comment]
thank you
