### ISSUE TITLE
Crash on Venus

### ISSUE THREAD

**Issue by masterjar** [4-Space/4-Space-1.7#36]
Using Space Astronomy mod pack. Game crashes on start now that I have reached Venus. Won't load long enough before crash to do anything. 

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 11/9/15 4:31 PM
Description: Ticking player

java.lang.ArithmeticException: / by zero
at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.checkThermalStatus(GCPlayerHandler.java:497)
at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1204)
at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:241)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_155_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295)
at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source)
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java)
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.checkThermalStatus(GCPlayerHandler.java:497)
at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1204)
at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:241)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_155_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
Entity ID: 2897
Entity Name: masterjar
Entity's Exact location: 199.67, 93.00, 7.04
Entity's Block location: World: (199,93,7), Chunk: (at 7,5,7 in 12,0; contains blocks 192,0,0 to 207,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Entity's Momentum: 0.00, -0.03, 0.00
Stacktrace:
at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295)
at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source)
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java)
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
Connection: net.minecraft.network.NetworkManager@35cc2f2
Stacktrace:
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 2120452104 bytes (2022 MB) / 3369074688 bytes (3213 MB) up to 5726797824 bytes (5461 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 161 mods loaded, 161 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} Minecraft Coder Pack 
UCHIJAAAA FML{7.10.99.99} Forge Mod Loader 
UCHIJAAAA Forge{10.13.4.1517} Minecraft Forge 
UCHIJAAAA appliedenergistics2-core{rv2-stable-10} AppliedEnergistics2 Core 
UCHIJAAAA Aroma1997Core{1.0.2.16} Aroma1997Core 
UCHIJAAAA CodeChickenCore{1.0.7.47} CodeChicken Core 
UCHIJAAAA Micdoodlecore{} Micdoodle8 Core 
UCHIJAAAA NotEnoughItems{1.0.5.118} Not Enough Items 
UCHIJAAAA OpenComputers|Core{1.5.19.37} OpenComputers (Core) 
UCHIJAAAA PlayerAPI{1.4} Player API 
UCHIJAAAA OpenModsCore{0.8} OpenModsCore 
UCHIJAAAA {000} CoFH ASM 
UCHIJAAAA {0} DragonAPI ASM Data Initialization 
UCHIJAAAA bspkrsCore{6.16} bspkrsCore 
UCHIJAAAA ArmorStatusHUD{1.28} ArmorStatusHUD 
UCHIJAAAA DamageIndicatorsMod{3.2.3} Damage Indicators 
UCHIJAAAA CoFHCore{1.7.10R3.0.3} CoFH Core 
UCHIJAAAA IC2{2.2.791-experimental} IndustrialCraft 2 
UCHIJAAAA advancedgenetics{1.5.9} Advanced Genetics 
UCHIJAAAA AdvancedSolarPanel{1.7.10-3.5.1} Advanced Solar Panels 
UCHIJAAAA appliedenergistics2{rv2-stable-10} Applied Energistics 2 
UCHIJAAAA bdlib{1.9.3.107} BD Lib 
UCHIJAAAA ae2stuff{0.5.0.56} AE2 Stuff 
UCHIJAAAA Aroma1997CoreHelper{1.0.2.16} Aroma1997Core|Helper 
UCHIJAAAA Aroma1997sDimension{1.0} Aroma1997's Dimensional World 
UCHIJAAAA BiblioCraft{1.11.3} BiblioCraft 
UCHIJAAAA ThermalFoundation{1.7.10R1.2.0} Thermal Foundation 
UCHIJAAAA ThermalExpansion{1.7.10R4.0.3B1} Thermal Expansion 
UCHIJAAAA BigReactors{0.4.3A} Big Reactors 
UCHIJAAAA BiomesOPlenty{2.1.0} Biomes O' Plenty 
UCHIJAAAA BuildCraft|Core{7.1.12} BuildCraft 
UCHIJAAAA BuildCraft|Builders{7.1.12} BC Builders 
UCHIJAAAA BuildCraft|Transport{7.1.12} BC Transport 
UCHIJAAAA BuildCraft|Energy{7.1.12} BC Energy 
UCHIJAAAA BuildCraft|Silicon{7.1.12} BC Silicon 
UCHIJAAAA BuildCraft|Robotics{7.1.12} BC Robotics 
UCHIJAAAA BuildCraft|Factory{7.1.12} BC Factory 
UCHIJAAAA CarpentersBlocks{3.3.7} Carpenter's Blocks 
UCHIJAAAA ChickenChunks{1.3.4.19} ChickenChunks 
UCHIJAAAA Railcraft{9.8.0.0} Railcraft 
UCHIJAAAA ForgeMultipart{1.2.0.345} Forge Multipart 
UCHIJAAAA chisel{2.5.1.44} Chisel 2 
UCHIJAAAA ChiselFacades{1.7.10-2.11-cricket} Chisel Facades 
UCHIJAAAA ComputerCraft{1.74} ComputerCraft 
UCHIJAAAA MineFactoryReloaded{1.7.10R2.8.0} MineFactory Reloaded 
UCHIJAAAA GalacticraftCore{3.0.12} Galacticraft Core 
UCHIJAAAA Mekanism{8.1.7} Mekanism 
UCHIJAAAA EnderIO{1.7.10-2.2.8.381} Ender IO 
UCHIJAAAA numina{0.4.0.131} Numina 
UCHIJAAAA MrTJPCoreMod{1.1.0.31} MrTJPCore 
UCHIJAAAA ProjRed|Core{4.7.0pre9.92} ProjectRed Core 
UCHIJAAAA powersuits{0.11.0.283} MachineMuse's Modular Powersuits 
UCHIJAAAA ExtraUtilities{1.2.12} Extra Utilities 
UCHIJAAAA ImmersiveEngineering{0.5.4} Immersive Engineering 
UCHIJAAAA Mantle{1.7.10-0.3.2.jenkins191} Mantle 
UCHIJAAAA Waila{1.5.10} Waila 
UCHIJAAAA TConstruct{1.7.10-1.8.8.build988} Tinkers' Construct 
UCHIJAAAA DragonAPI{1.0} DragonAPI 
UCHIJAAAA ChromatiCraft{1.0} ChromatiCraft 
UCHIJAAAA EnderStorage{1.4.7.37} EnderStorage 
UCHIJAAAA ProjRed|Transmission{4.7.0pre9.92} ProjectRed Transmission 
UCHIJAAAA OpenComputers{1.5.19.37} OpenComputers 
UCHIJAAAA CompactMachines{1.7.10-1.20} Compact Machines 
UCHIJAAAA CustomMainMenu{1.7.1} Custom Main Menu 
UCHIJAAAA ImmibisCore{59.1.2} Immibis Core 
UCHIJAAAA DimensionalAnchors{59.0.3} Dimensional Anchors 
UCHIJAAAA Eln{50} Electrical Age 
UCHIJAAAA RotaryCraft{1.0} RotaryCraft 
UCHIJAAAA ElectriCraft{1.0} ElectriCraft 
UCHIJAAAA eplus{3.0.2-d} Enchanting Plus 
UCHIJAAAA EnderTech{1.7.10-0.3.2.405} EnderTech 
UCHIJAAAA enhancedportals{3.0.12} EnhancedPortals 
UCHIJAAAA extracells{2.2.73} Extra Cells 2 
UCHIJAAAA FastCraft{1.21} FastCraft 
UCHIJAAAA GalacticraftMars{3.0.12} Galacticraft Planets 
UCHIJAAAA GraviSuite{1.7.10-2.0.3} Graviation Suite 
UCHIJAAAA iChunUtil{4.2.2} iChunUtil 
UCHIJAAAA Hats{4.0.1} Hats 
UCHIJAAAA HardcoreQuesting{The Journey (4.2.4)} Hardcore Questing Mode 
UCHIJAAAA IC2NuclearControl{2.2.5a-GoingForTheKill} Nuclear Control 2 
UCHIJAAAA IGWMod{1.1.11-32} In-Game wiki Mod 
UCHIJAAAA immersiveintegration{0.5.4} Immersive Integration 
UCHIJAAAA LunatriusCore{1.1.2.21} LunatriusCore 
UCHIJAAAA InGameInfoXML{2.8.1.82} InGame Info XML 
UCHIJAAAA inventorytweaks{1.59-dev-152-cf6e263} Inventory Tweaks 
UCHIJAAAA IronChest{6.0.62.742} Iron Chest 
UCHIJAAAA journeymap{5.1.1b9} JourneyMap 
UCHIJAAAA LogisticsPipes{0.9.3.67} Logistics Pipes 
UCHIJAAAA MekanismGenerators{8.1.7} MekanismGenerators 
UCHIJAAAA MekanismTools{8.1.7} MekanismTools 
UCHIJAAAA ReactorCraft{1.0} ReactorCraft 
UCHIJAAAA Mimicry{1.7.x_1286_1.0.9} Mimicry 
UCHIJAAAA MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} MFR Compat: Applied Energistics 
UCHIJAAAA MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} MFR Compat: Atum 
UCHIJAAAA MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} MFR Compat: BackTools 
UCHIJAAAA MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} MFR Compat: BuildCraft 
UCHIJAAAA MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} MFR Compat: Chococraft 
UCHIJAAAA MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} MFR Compat: ExtraBiomes 
UCHIJAAAA MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} MFR Compat: Forestry 
UCHIJAAAA MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} MFR Compat: ForgeMicroblock 
UCHIJAAAA MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} MFR Compat: IC2 
UCHIJAAAA MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} MFR Compat: Mystcraft 
UCHIJAAAA ProjRed|Exploration{4.7.0pre9.92} ProjectRed Exploration 
UCHIJAAAA MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} MFR Compat ProjectRed 
UCHIJAAAA MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} MFR Compat: Railcraft 
UCHIJAAAA MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} MFR Compat: Sufficient Biomes 
UCHIJAAAA MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} MFR Compat: Thaumcraft 
UCHIJAAAA MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} MFR Compat: Thermal Expansion 
UCHIJAAAA MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} MFR Compat: Tinkers' Construct 
UCHIJAAAA MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} MFR Compat: TwilightForest 
UCHIJAAAA MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} MFR Compat: Vanilla 
UCHIJAAAA MineTweaker3{3.0.10} MineTweaker 3 
UCHIJAAAA MTRM{1.0} MineTweakerRecipeMaker 
UCHIJAAAA MorePlanet{1.3.0} More Planets 
UCHIJAAAA cfm{3.4.8} §9MrCrayfish's Furniture Mod 
UCHIJAAAA NEIAddons{1.12.13.38} NEI Addons 
UCHIJAAAA NEIAddons|Developer{1.12.13.38} NEI Addons: Developer Tools 
UCHIJAAAA NEIAddons|AppEng{1.12.13.38} NEI Addons: Applied Energistics 2 
UCHIJAAAA NEIAddons|Botany{1.12.13.38} NEI Addons: Botany 
UCHIJAAAA NEIAddons|Forestry{1.12.13.38} NEI Addons: Forestry 
UCHIJAAAA NEIAddons|CraftingTables{1.12.13.38} NEI Addons: Crafting Tables 
UCHIJAAAA NEIAddons|ExNihilo{1.12.13.38} NEI Addons: Ex Nihilo 
UCHIJAAAA neiintegration{1.0.13} NEI Integration 
UCHIJAAAA NEIPlugins{1.1.0.8-unofficial} NEI Plugins Unofficial 
UCHIJAAAA OpenMods{0.8} OpenMods 
UCHIJAAAA OpenBlocks{1.4.4} OpenBlocks 
UCHIJAAAA openmodularturrets{2.1.5-184} Open Modular Turrets 
UCHIJAAAA OpenPeripheralCore{1.2} OpenPeripheralCore 
UCHIJAAAA OpenPeripheral{0.4} OpenPeripheralAddons 
UCHIJAAAA OpenPeripheralIntegration{0.3} OpenPeripheralIntegration 
UCHIJAAAA harvestcraft{1.7.10j} Pam's HarvestCraft 
UCHIJAAAA PneumaticCraft{1.11.18-140} PneumaticCraft 
UCHIJAAAA PowerConverters{1.7.10_3.3.0-jenkins.76} Power Converters 
UCHIJAAAA JotatosPracticalities{0.6.2} Practicalities 
UCHIJAAAA ProjRed|Transportation{4.7.0pre9.92} ProjectRed Transportation 
UCHIJAAAA ProjRed|Compatibility{4.7.0pre9.92} ProjectRed Compatibility 
UCHIJAAAA ProjRed|Integration{4.7.0pre9.92} ProjectRed Integration 
UCHIJAAAA ProjRed|Fabrication{4.7.0pre9.92} ProjectRed Fabrication 
UCHIJAAAA ProjRed|Illumination{4.7.0pre9.92} ProjectRed Illumination 
UCHIJAAAA ProjRed|Expansion{4.7.0pre9.92} ProjectRed Expansion 
UCHIJAAAA QuarryPlus{2.1.0} QuarryPlus 
UCHIJAAAA RandomThings{2.2.4} Random Things 
UCHIJAAAA RedstoneArsenal{1.7.10R1.1.1} Redstone Arsenal 
UCHIJAAAA RedstonePasteMod{1.6.2} Redstone Paste 
UCHIJAAAA simplyjetpacks{1.5.1} Simply Jetpacks 
UCHIJAAAA SlimevoidLib{2.0.4.6} Slimevoid Library 
UCHIJAAAA SolarFlux{1.7.10-0.8b} Solar Flux 
UCHIJAAAA SSR{rc3} Soul Shards Reborn 
UCHIJAAAA Sync{4.0.0} Sync 
UCHIJAAAA ThermalDynamics{1.7.10R1.1.0} Thermal Dynamics 
UCHIJAAAA TiCTooltips{1.2.5} TiC Tooltips 
UCHIJAAAA VeinMiner{0.30.0_build.unknown} Vein Miner 
UCHIJAAAA VeinMinerModSupport{0.30.0_build.unknown} Mod Support 
UCHIJAAAA WailaHarvestability{1.1.5} Waila Harvestability 
UCHIJAAAA WirelessRedstoneCore{1.8.0.0} Wireless Redstone 
UCHIJAAAA yampst{1.3.5} YAMPST 
UCHIJAAAA McMultipart{1.2.0.345} Minecraft Multipart Plugin 
UCHIJAAAA ForgeRelocation{0.0.1.4} ForgeRelocation 
UCHIJAAAA MCFrames{1.0} MCFrames 
UCHIJAAAA RelocationFMP{0.0.1.2} RelocationFMP 
UCHIJAAAA ForgeMicroblock{1.2.0.345} Forge Microblocks 
GL info: ERROR RuntimeException: No OpenGL context found in the current thread.
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
CoFHCore: -[1.7.10]3.0.3-303
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
ThermalFoundation: -[1.7.10]1.2.0-102
ThermalExpansion: -[1.7.10]4.0.3B1-218
MineFactoryReloaded: -[1.7.10]2.8.0-104
Mantle Environment: Environment healthy.
TConstruct Environment: Environment healthy.
RedstoneArsenal: -[1.7.10]1.1.1-89
ThermalDynamics: -[1.7.10]1.1.0-161
List of loaded APIs: 
- appliedenergistics2|API (rv2) from DragonAPI 1.7.10 V9b.jar
- Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.0-102.jar
- BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1462-universal.jar
- BuildCraftAPI|blocks (1.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.12.jar
- BuildCraftAPI|boards (2.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
- BuildCraftAPI|crops (1.1) from buildcraft-7.1.12.jar
- BuildCraftAPI|events (2.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|facades (1.1) from buildcraft-7.1.12.jar
- BuildCraftAPI|filler (4.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|fuels (2.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|gates (4.1) from buildcraft-7.1.12.jar
- BuildCraftAPI|items (1.1) from buildcraft-7.1.12.jar
- BuildCraftAPI|library (2.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|lists (1.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|power (1.3) from buildcraft-7.1.12.jar
- BuildCraftAPI|recipes (3.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|robotics (3.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|statements (1.1) from buildcraft-7.1.12.jar
- BuildCraftAPI|tablet (1.0) from buildcraft-7.1.12.jar
- BuildCraftAPI|tiles (1.2) from buildcraft-7.1.12.jar
- BuildCraftAPI|tools (1.0) from EnhancedPortals_1.7.10-universal-3.0.12.jar
- BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.8.0.0.jar
- CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
- ChiselAPI (0.1.0) from Chisel2-2.5.1.44.jar
- ChiselAPI|Carving (0.1.0) from Chisel2-2.5.1.44.jar
- ChiselAPI|Rendering (0.1.0) from Chisel2-2.5.1.44.jar
- CoFHAPI (1.7.10R1.0.2) from IC2NuclearControl-2.2.5a-GoingForTheKill.jar
- CoFHAPI|block (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
- CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHAPI|energy (1.7.10R1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
- CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHAPI|inventory (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHAPI|item (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHAPI|transport (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
- CoFHAPI|world (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|audio (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHLib|gui (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHLib|gui|container (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|util (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHLib|util|helpers (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHLib|util|position (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
- CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
- ComputerCraft|API (1.74) from ComputerCraft1.74.jar
- ComputerCraft|API|FileSystem (1.74) from ComputerCraft1.74.jar
- ComputerCraft|API|Lua (1.74) from ComputerCraft1.74.jar
- ComputerCraft|API|Media (1.74) from ComputerCraft1.74.jar
- ComputerCraft|API|Peripheral (1.74) from ComputerCraft1.74.jar
- ComputerCraft|API|Permissions (1.74) from ComputerCraft1.74.jar
- ComputerCraft|API|Redstone (1.74) from ComputerCraft1.74.jar
- ComputerCraft|API|Turtle (1.74) from ComputerCraft1.74.jar
- EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
- EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
- EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
- ForgeRelocation|API (0.0.1.4) from ForgeRelocation-1.7.10-0.0.1.4-universal.jar
- Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.402.jar
- IC2API (1.0) from Railcraft_1.7.10-9.8.0.0.jar
- ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.5.4.jar
- MekanismAPI|core (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|energy (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|gas (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|infuse (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|laser (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|reactor (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|recipe (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|transmitter (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- MekanismAPI|util (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
- minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V9b.jar
- NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.2.5a-GoingForTheKill.jar
- OpenBlocks|API (1.0) from OpenBlocks-1.7.10-1.4.4.jar
- OpenComputersAPI|Component (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Core (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Driver (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Driver|Item (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Event (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|FileSystem (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Internal (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Machine (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Manual (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Network (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenComputersAPI|Prefab (5.6.2) from OpenComputers-MC1.7.10-1.5.19.37-universal.jar
- OpenPeripheralApi (3.3.1) from OpenPeripheral-1.7.10-AIO-5.jar
- PneumaticCraftApi (1.0) from PneumaticCraft-1.7.10-1.11.18-140-universal.jar
- RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.8.0.0.jar
- RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.8.0.0.jar
- Thaumcraft|API (4.2.2.0) from Pam's HarvestCraft 1.7.10k.jar
- VeinMinerApi (0.1) from VeinMiner-1.7.10_0.30.0.unknown.jar
- WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
  Stencil buffer state: Function set: GL30, pool: forge, bits: 8
  AE2 Integration: IC2:ON, RotaryCraft:ON, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
  Profiler Position: N/A (disabled)
  Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
  Player Count: 1 / 8; [EntityPlayerMP['masterjar'/2897, l='MAUSA', x=199.67, y=93.00, z=7.04]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by mattparks** [comment]
Try updating galacticraft too the latest beta release, the problem is the player time is getting a value of 0 and the math is trying too devide a value by it.

**Comment by masterjar** [comment]
I tried the newest versions of all 3 Galacticraft ,jars, and it seems like the save was corrupted. I was able to pull up an old save, and will take a break before recreating a weeks worth of work. Hopefully my next trip to Venus goes better, and I will backup before I go this time.
